# Generated by Django 5.0.4 on 2024-04-25 03:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_concersationmessage_id_alter_conversation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConcersationMessage',
            new_name='ConversationMessage',
        ),
    ]
