# Generated by Django 5.0.4 on 2024-05-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_by',
        ),
    ]
