# Generated by Django 5.0.4 on 2024-04-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_concersationmessage_conversationmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='users',
        ),
    ]
