# Generated by Django 5.0.4 on 2024-04-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
