# Generated by Django 5.0.4 on 2024-04-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_posts_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
    ]
